Repository datalad/datalad-neuroimaging, pull requests merged in 2024-03, with the labels that each got.

#130 Set up releasing workflows
  .datalad-release-action.yaml
  .github/workflows/add-changelog-snippet.yml
  .github/workflows/release.yml
  CHANGELOG.md
  changelog.d/pr-130.md
  changelog.d/scriv.ini
  changelog.d/templates/entry_title.md.j2
  changelog.d/templates/new_fragment.md.j2
Labels: semver-internal

#132 Fixup intersphinx_mapping for python
  changelog.d/pr-132.md
  docs/source/conf.py
Labels: semver-documentation

#131 Add codespell config and workflow, and use it to typos found throughout the codebase
  .appveyor.yml
  .github/workflows/codespell.yml
  Makefile
  _datalad_buildsupport/formatters.py
  changelog.d/pr-131.md
  datalad_neuroimaging/__init__.py
  datalad_neuroimaging/bids2scidata.py
  datalad_neuroimaging/extractors/nifti1.py
  datalad_neuroimaging/extractors/tests/test_nifti1.py
  datalad_neuroimaging/tests/test_search.py
  formatters.py
  pyproject.toml
Labels: semver-patch, release
